/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Receipt = IDL.Record({
  'id' : IDL.Nat,
  'gst' : IDL.Text,
  'customerName' : IDL.Text,
  'dateOfExpiry' : IDL.Text,
  'total' : IDL.Text,
  'duration' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'balance' : IDL.Text,
  'userId' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'speedPlan' : IDL.Text,
  'grandTotal' : IDL.Text,
  'address' : IDL.Text,
  'packageValue' : IDL.Text,
  'receiptNo' : IDL.Text,
  'mobile' : IDL.Text,
  'installationCharges' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReceipt' : IDL.Func([Receipt], [Receipt], []),
  'deleteReceipt' : IDL.Func([IDL.Nat], [], []),
  'getAllReceiptsDesc' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNextReceiptNo' : IDL.Func([], [IDL.Nat], ['query']),
  'getReceipt' : IDL.Func([IDL.Nat], [Receipt], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateReceipt' : IDL.Func([IDL.Nat, Receipt], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Receipt = IDL.Record({
    'id' : IDL.Nat,
    'gst' : IDL.Text,
    'customerName' : IDL.Text,
    'dateOfExpiry' : IDL.Text,
    'total' : IDL.Text,
    'duration' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'balance' : IDL.Text,
    'userId' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'speedPlan' : IDL.Text,
    'grandTotal' : IDL.Text,
    'address' : IDL.Text,
    'packageValue' : IDL.Text,
    'receiptNo' : IDL.Text,
    'mobile' : IDL.Text,
    'installationCharges' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReceipt' : IDL.Func([Receipt], [Receipt], []),
    'deleteReceipt' : IDL.Func([IDL.Nat], [], []),
    'getAllReceiptsDesc' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNextReceiptNo' : IDL.Func([], [IDL.Nat], ['query']),
    'getReceipt' : IDL.Func([IDL.Nat], [Receipt], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateReceipt' : IDL.Func([IDL.Nat, Receipt], [], []),
  });
};

export const init = ({ IDL }) => { return []; };